name: Docker Image CI

on:
  release:
    types: [published]

permissions:
  packages: write

jobs:

  build:

    runs-on: ubuntu-latest

    steps:        
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ghcr.io/alex-merge/weather-report:latest -t ghcr.io/alex-merge/weather-report:$(date +%s)
    - name: Login to Docker
      run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
    - name: Push the Docker container
      run: docker image push --all-tags ghcr.io/alex-merge/weather-report
